package com.mili.net.utils

const val ERROR_CODE_SUCCESS = "200"
const val ERROR_CODE_TOKEN_EXPIRED = "BK0003"
const val ERROR_CODE_REFRESH_TOKEN_EXPIRED = "BK0006"
const val ERROR_CODE_SIGNATURE_INVAILIED = "B40001"
const val ERROR_CODE_USER_NOT_EXIST = "BU0005"
const val ERROR_CODE_MOBILE_EXIST = "BU0001"